### ISSUE TITLE
Incorrect minimum Python version

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/plum-dispatch-feedstock#49]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This conda-forge package indicates `python >=3.7` as its Python dependency.  However, as seen in the [Github repo](https://github.com/beartype/plum/blob/v2.2.0/pyproject.toml), the upstream project has required `python >=3.8` since plum v2.2.0.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by wesselb** [comment]
Hey @DManowitz! You're completely right. I've updated the recipe, so this should hopefully be correct now. :) Thanks for opening an issue! Much appreciated.
